### ISSUE TITLE
Error parsing a meta element's content

### ISSUE THREAD

**Issue by 1Tado1** [xieqifei/AutoLernraum#1]
Double checked the random_test.py file. This is the result code everytime after executing the file

`[1110/123418.067:INFO:CONSOLE(1)] "The Content Security Policy directive 'frame-ancestors' is ignored when delivered via a <meta> element.", source: https://buchung.hsz.rwth-aachen.de/angebote/aktueller_zeitraum/_Lernraumbuchung.html (1)`
`[1110/123418.069:INFO:CONSOLE(1)] "The Content Security Policy directive 'frame-ancestors' is ignored when delivered via a <meta> element.", source: https://buchung.hsz.rwth-aachen.de/angebote/aktueller_zeitraum/_Lernraumbuchung.html (1)`
`2021-11-10 12:34:18: refresh page`
`2021-11-10 12:34:18: refresh page`
`[1110/123418.572:INFO:CONSOLE(2)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: https://buchung.hsz.rwth-aachen.de/cgi/anmeldung.fcgi (2)`
`[1110/123418.579:INFO:CONSOLE(2)] "Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.", source: https://buchung.hsz.rwth-aachen.de/cgi/anmeldung.fcgi (2)`

**Comment by xieqifei** [comment]
This is due to your terminal. You can ignore it. When "refresh page" appears, the programm is running.

**Comment by xieqifei** [comment]
In my terminal the console Info is not displayed.
