### ISSUE TITLE
IP Banned?

### ISSUE THREAD

**Issue by 1Tado1** [xieqifei/AutoLernraum#2]
just thought to let you know, that I think they excluded my local IP adress(or something). Had the script running some time in multiple instances (1 for early and 1 form late booking exclusively) and I'm not able to access the buchungs-site within my local internet-network anymore. Works fine within other networks and VPN. Be carefuell i guess

**Comment by xieqifei** [comment]
This problem is common. A simple solution is rebooting your router. Then a new IP will be given. VPN is strongly recommend.
