### ISSUE TITLE
Error 504: Gateway Timeout

### ISSUE THREAD

**Issue by wghaotian** [xieqifei/AutoLernraum#4]
大佬你好，当发生Error 504的时候是否能让程序退回去再次提交表单，而不是直接终止程序？我们在手动操作时遇到这种情况是可以这么去做的。
![image](https://user-images.githubusercontent.com/34622764/149623282-4275e78a-8581-4294-80f1-79a318068320.png)

**Comment by xieqifei** [comment]
你好，我注意到你的日志中显示你在第47秒才开始预定进程，这对于抢座来说已经太慢了。你可能在使用random_test.py来抢座，此程序无法准点运行，每两次运行时，总有20秒的等待间隔。。建议你使用test_selenium.py进行定时抢座，通常"found available booking button"日志在抢座准点后的5秒钟之内出现是正常。。504的出现是由于服务器承受了过多负载，而导致服务器无法处理全部的请求，正常情况下，抢座程序会在服务器尚未发生拥挤前完成任务，因此504是不会出现的（至少我从未遇见过）。由于系统改变了他的预定时间，程序会在稍后做些修改提交。。感谢你的反馈！

**Comment by wghaotian** [comment]
> 此

**Comment by wghaotian** [comment]
是这样的，如图，前47秒它一直在尝试刷新界面……不过最后还是收到预定成功的确认邮件了，感谢大佬！
![image](https://user-images.githubusercontent.com/34622764/149628049-7e40c2f9-337c-4813-8d37-cf0c6fa619b4.png)
